"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var semver = require("semver");
exports.semver = semver;
var server_1 = require("@platform/log/lib/server");
exports.log = server_1.log;
var exec_1 = require("@platform/exec");
exports.exec = exec_1.exec;
var util_value_1 = require("@platform/util.value");
exports.value = util_value_1.value;
var npm_1 = require("@platform/npm");
exports.npm = npm_1.npm;
var fs_1 = require("@platform/fs");
exports.fs = fs_1.fs;
var command_interface_1 = require("command-interface");
exports.moment = command_interface_1.moment;
exports.file = command_interface_1.file;
exports.listr = command_interface_1.listr;
exports.inquirer = command_interface_1.inquirer;
exports.plural = command_interface_1.plural;
var R = require("ramda");
exports.R = R;
